### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LiuN1an** [bananaml/demo-automatic1111-sd-webui#1]
When I deployed the project to banana and send the post request to https://xxxx.run.banana.dev/txt2img, it responsed:

`An error occured. 
	Type: PotassiumError 
	StatusCode: 500 
	Message: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/potassium/potassium.py", line 114, in _handle_generic
    out = endpoint.func(req)
  File "/opt/conda/lib/python3.8/site-packages/potassium/potassium.py", line 67, in wrapper
    out = func(self._context, request)
  File "<string>", line 100, in handler
TypeError: 'NoneType' object is not subscriptable`

The payload of the request is
`{
    "params": {
        "prompt": "a cute dog",
        "negative_prompt": "low quality",
        "steps": 25,
        "sampler_name": "Euler a",
        "cfg_scale": 7.5,
        "seed": 42,
        "batch_size": 1,
        "n_iter": 1,
        "width": 400,
        "height": 400,
        "tiling": "false"
    }
}`

how to fix it?

**Comment by LiuN1an** [comment]
More, even if the response fails, I will be charged $0.20 per request,
